name: PR Build

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: common/temp/pnpm-store
        key: ${{ runner.os }}-rush-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-rush-pnpm-
          
    - name: Setup Rush build cache
      uses: actions/cache@v4
      with:
        path: common/temp/build-cache
        key: ${{ runner.os }}-rush-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-rush-build-
          
    - name: Rush install
      run: node common/scripts/install-run-rush.js install
      
    - name: Rush build
      run: node common/scripts/install-run-rush.js build
      
    - name: Generate documentation
      run: node common/scripts/install-run-rush.js generate-docs
      
    - name: Validate Rush configuration
      run: |
        echo "Validating Rush configuration..."
        node common/scripts/install-run-rush.js --help > /dev/null
        echo "✓ Rush configuration is valid"
        
    - name: Check for build artifacts
      run: |
        echo "Checking for built files..."
        ls -la vscode-extension-toolkit/lib/
        ls -la vscode-extension-toolkit/docs/markdown/
        echo "Build artifacts verified!"
