name: Release and Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Verify Rush installation
      run: node common/scripts/install-run-rush.js --version
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: common/temp/pnpm-store
        key: ${{ runner.os }}-rush-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-rush-pnpm-
          
    - name: Setup Rush build cache
      uses: actions/cache@v4
      with:
        path: common/temp/build-cache
        key: ${{ runner.os }}-rush-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-rush-build-
          
    - name: Rush install
      run: node common/scripts/install-run-rush.js install
      
    - name: Rush build
      run: node common/scripts/install-run-rush.js build
      
    - name: Generate documentation
      run: node common/scripts/install-run-rush.js generate-docs
      
    - name: Verify package contents
      run: |
        echo "Package contents that will be published:"
        cd vscode-extension-toolkit
        npm pack --dry-run
        
    - name: Log working directory state
      run: |
        echo "Logging working directory state before publishing..."
        git status
        git diff

    - name: Publish to NPM
      run: |
        cd vscode-extension-toolkit
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
